# Generated by Django 4.2.19 on 2025-11-23 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeknoparkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('weekly_working_hours', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Haftalık Çalışma Saati')),
                ('weekly_working_days', models.PositiveIntegerField(default=5, verbose_name='Haftalık Çalışma Günü')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teknopark_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeknoparkPDKSMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('month', models.PositiveIntegerField(choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], verbose_name='Ay')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Toplam Süre (Saat)')),
                ('required_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Gerekli Süre (Saat)')),
                ('remaining_hours', models.DecimalField(decimal_places=2, default=0.0, help_text="O gün teknopark'ta geçirilen kalan süre", max_digits=5, verbose_name='Kalan Süre (Saat)')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Toplam Gün Sayısı')),
                ('average_hours_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Günlük Ortalama (Saat)')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Son Hesaplama')),
                ('teknopark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdks_monthly_reports', to='teknopark.teknoparkuser', verbose_name='Teknopark Kullanıcı')),
            ],
            options={
                'verbose_name': 'PDKS Aylık Rapor',
                'verbose_name_plural': 'PDKS Aylık Raporlar',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['teknopark_user', 'year', 'month'], name='teknopark_t_teknopa_d90cd2_idx')],
                'unique_together': {('teknopark_user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TeknoparkPDKSEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('entry', 'Giriş'), ('exit', 'Çıkış')], max_length=10, verbose_name='PDKS Log Tipi')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Giriş veya çıkış zamanı', verbose_name='Zaman')),
                ('teknopark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdkse_entry_logs', to='teknopark.teknoparkuser', verbose_name='Teknopark Kullanıcı')),
            ],
            options={
                'verbose_name': 'PDKS Giriş Logu',
                'verbose_name_plural': 'PDKS Giriş Logları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['teknopark_user', 'timestamp'], name='teknopark_t_teknopa_0b211d_idx'), models.Index(fields=['teknopark_user', 'log_type', 'timestamp'], name='teknopark_t_teknopa_dab0a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeknoparkPDKSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, help_text="O gün teknopark'ta geçirilen toplam süre", max_digits=5, verbose_name='Toplam Süre (Saat)')),
                ('entry_count', models.PositiveIntegerField(default=0, verbose_name='Giriş Sayısı')),
                ('first_entry', models.DateTimeField(blank=True, null=True, verbose_name='İlk Giriş')),
                ('last_exit', models.DateTimeField(blank=True, null=True, verbose_name='Son Çıkış')),
                ('teknopark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdks_entries', to='teknopark.teknoparkuser', verbose_name='Teknopark Kullanıcı')),
            ],
            options={
                'verbose_name': 'Günlük Yoklama',
                'verbose_name_plural': 'Günlük Yoklamalar',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['teknopark_user', 'date'], name='teknopark_t_teknopa_14c9c4_idx')],
                'unique_together': {('teknopark_user', 'date')},
            },
        ),
    ]
